# Generated by Django 5.1.1 on 2024-09-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_perfilusuario_preferencias_alimenticias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='preferencias_alimenticias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
