# Generated by Django 5.1.1 on 2024-09-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_alter_perfilusuario_preferencias_alimenticias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='grupo_perfiles/'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='grupo_portadas/'),
        ),
    ]
